LIBS = -lm -D_INTEL
SOURCE = cvProgramming.c readBmpFile.c writeBmpFile.c executeChromakey.c executeKMeans.c executeNegative.c executeScale.c executeSpaceFiltering.c executeVirtualStudio.c executeBinalization.c executeGammaCorrection.c  executeAlphaBlending.c 
cv: $(SOURCE)
	gcc -o cv $(SOURCE) $(LIBS)
